Position.cs
Lerokaa/Lab2 pull request #12
Opened 2024-04-20 07:58 UTC by fr33tut

2024-04-20 08:22 UTC, Lerokaa requested changes
![image](https://github.com/Lerokaa/Lab2/assets/151133526/86fe5a01-0bcd-443b-9ad4-8775e0f72e29)

2024-04-20 08:22 UTC, Lerokaa commented on ClassLibrary/Position.cs
> +        }
это должны быть свойства с доступом на чтение

2024-04-20 08:22 UTC, Lerokaa commented on ClassLibrary/Position.cs
> +        private string Department;
закрытые поля пишутся с маленькой буквы

2024-04-20 08:22 UTC, Lerokaa commented on ClassLibrary/Position.cs
> +        private string Department;
Подразделение должна быть ссылка

2024-05-18 08:08 UTC, YuriSilenok requested changes
Нет ссылки на вариант

2024-05-18 08:08 UTC, YuriSilenok commented on ClassLibrary/Position.cs
> +        private string department;
Подразделение должно быть ссылкой

2024-06-01 07:13 UTC, Lerokaa commented
Где изменения?

2024-06-01 07:50 UTC, merged