Var5
Lerokaa/Lab2 pull request #16
Opened 2024-04-20 08:24 UTC by StAruYViTal9

2024-04-20 08:28 UTC, Lerokaa requested changes
Код хороший, но есть ошибки
![image](https://github.com/Lerokaa/Lab2/assets/151133526/7e47f3ae-704e-4dfb-8445-2384e28d1135)

2024-04-20 08:29 UTC, Lerokaa commented
решите конфликт версий

2024-05-18 08:25 UTC, YuriSilenok requested changes
В чем разница между Auditorium и Classroom?

2024-06-01 07:10 UTC, Lerokaa submitted a review, later dismissed

2024-06-01 09:34 UTC, closed without merging