var4
Lerokaa/Lab2 pull request #19
Opened 2024-05-03 18:40 UTC by blupochkaa

2024-05-04 08:04 UTC, insomnira commented
Hello, dear Kate! I'm sorry that I haven't written for a long time 💌🌸

2024-05-18 08:14 UTC, YuriSilenok requested changes
- нет ссылки на вариант
- нужно реализовать CreateGroup, PrintGroup

2024-05-31 20:29 UTC, blupochkaa commented
![sticker](https://github.com/Lerokaa/Lab2/assets/148614664/267b91de-3610-4284-a001-d97591f3a20b)

2024-06-01 07:09 UTC, Lerokaa approved these changes, later dismissed

2024-06-01 09:34 UTC, closed without merging