pull request var7
Lerokaa/Lab2 pull request #21
Opened 2024-05-11 19:25 UTC by xKernelPx

add Pair.cs

2024-05-18 08:16 UTC, YuriSilenok requested changes
Нет ссылки на вариант

2024-05-18 08:16 UTC, YuriSilenok commented on ClassLibrary/Pair.cs
> +		private DateTime _timeRestEnd;
Структура для хранения времени TimeSpan

2024-06-01 07:12 UTC, Lerokaa reviewed
а где Creation, Printer, Main, DB?

2024-06-01 08:52 UTC, xKernelPx commented
Добавлены изменения в Creator, DB, Program, Printer, изменён тип DateTime на TimeSpan

2024-06-01 09:34 UTC, closed without merging